# Generated by Django 2.1.8 on 2019-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190609_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_image',
            field=models.FileField(upload_to='pictures'),
        ),
    ]
